[modules]
left = [ "Workspaces" ]
center = [ "WindowTitle" ]
right = [ "Updates", "SystemInfo", "Tray", [ "Clock", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'kitty -e  bash -c "yay; echo Done - Press enter to exit; read" &'

[appearance]

success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = [ "#fab387", "#b4befe", "#cba6f7" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
